### ISSUE TITLE
API Naming inconsistencies - pronoun usage

### ISSUE THREAD

**Issue by ciscorucinski** [florent37/KotlinPleaseAnimate#3]
Some of the API's use `His` while another use `Its`. Stay consistent.

Why did you change from no pronouns in the Java version of the API to pronouns in the  Kotlin version? I suggest you use `Its` if you want a pronoun, or just drop it completely (suggested). I don't usually think of a guy when I think about my views.

**Comment by florent37** [comment]
I'm just not an english native speaker,
Can you please help me sending the list of mistake I made, or directly a
pull request ? Thanks

Le 16 mars 2018 11:55, "Christopher Rucinski" <notifications@github.com> a
écrit :

**Comment by florent37** [comment]
fixed in 1.0.1, thanks for the issue 👍

**Comment by ciscorucinski** [comment]
Sorry, I didn't get the lost to you earlier. I just looked quick over the Readme and it seems more pleasant to read. Thanks ^^
