### ISSUE TITLE
Ability to create customAnimations

### ISSUE THREAD

**Issue by KirkBushman** [florent37/KotlinPleaseAnimate#4]
Hi, first of all awesome library, makes animation much more fun!

To the question: 

I'm trying to create other animations that are missing or for custom view.
I can do that by extending CustomAnimExpectation but I cannot add it to Expectations like all the other already present, because the list variable "expectations" is internal and not accessible.

Can we have it public? 
I think having the possibility to create custom animations on the fly (and contribute to the project) would add a lot of value to this lib.

Thanks in advance for the response.

**Comment by Jacare91** [comment]
I had same issue, maybe inline functions?

**Comment by KirkBushman** [comment]
Yes, that's what I was suggesting, I can create an inline function that extends the class AnimExpectations, but I can't add it to Expectations, so It wont work in the end (or at least I haven't found a simple way to do this).

I've forked the repo, maybe later I'll create a pull request to fix this issue, as it would be awesome to animate on android like this.

I hope the repo manager has intention to keep supporting this lib.

**Comment by florent37** [comment]
Hi, yes it's à good feature tout add, it Was on the java implementation,
i'll try add it on the kotlin version

**Comment by florent37** [comment]
in the 1.0.2 : 
```

please {
            
            animate(content) {
                outOfScreen(Gravity.BOTTOM)
                invisible()
                
                custom(object: CustomAnimExpectation() {
                    override fun getAnimator(viewToMove: View): Animator? {
                        return ObjectAnimator.ofFloat(viewToMove, "myMethod", 0f, 1f)
                    }
                })
                
            }
        }
```

(you can for sure create a class extending CustomAnimExpectation instead of a kotlin object)
